# Generated by Django 3.1.2 on 2020-10-09 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device_Found',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac_address', models.TextField()),
                ('ip_address', models.TextField()),
                ('os', models.CharField(max_length=200)),
                ('first_time', models.DateTimeField(auto_now=True)),
                ('last_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
