# Generated by Django 3.1.2 on 2020-10-09 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Device_Found',
            new_name='Devices',
        ),
    ]
